### ISSUE TITLE
WHITELIST not defined in environment but enforced regardless

### ISSUE THREAD

**Issue by skoranda** [TheIdentitySelector/thiss-js#28] opened 2020-01-30 20:26 UTC
I am using commit adef39a9bba30c9dba755ddeb5c757e5592b8206

I ran 'make standalone' and then deployed the code in dist/

The entrypoint script for my container does

cd /dist
for f in `find . -printf '%P\n'`; do
   if [ "x$f" != "x" -a -f $f ]; then
      d=`dirname $f`
      mkdir -p /usr/share/nginx/html/$d
      envsubst '${BASE_URL} ${PERSISTENCE_URL} ${MDQ_URL} ${SEARCH_URL} ${DEFAULT_CONTEXT}' < $f > /usr/share/nginx/html/$f
   fi
done

There is no WHITELIST defined for the process.

When I browse to the ds I see in the console log

Access denied from...

**Comment by leifj** [comment] 2020-01-30 23:08
Quoting those variables are hard... ”wfm”

Skickat från min iPhone

**Comment by leifj** [comment] 2020-03-10 08:26
I am not able to reproduce this... should I close this?

**Closed** 2020-05-19 12:14 UTC
